language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
script: make
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated llvm || brew upgrade llvm; fi
notifications:
  email: false
