language: c
cache: brew
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install clang-omp; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make CC=clang-omp; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
notifications:
  email: false
